# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='source',
            field=models.CharField(choices=[('SMS', 'Incoming SMS'), ('VCE', 'Incoming Voice'), ('WEB', 'From Web')], default='SMS', max_length=5),
        ),
    ]
