# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_notifications', '0002_notification_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_sid',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
