# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-17 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_notifications', '0004_auto_20171217_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message_sid',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
