# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-17 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_notifications', '0005_auto_20171217_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='datalive_cust_veh.Vehicle'),
        ),
    ]
