# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_notifications', '0006_auto_20171217_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notified_by',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
