# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-29 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_notifications', '0007_notification_notified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='source',
            field=models.CharField(choices=[('SMS', 'Incoming SMS'), ('VCE', 'Incoming Voice'), ('WEB', 'From Web'), ('CRON', 'Cron task')], default='SMS', max_length=5),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('panic', 'Panic button'), ('daily_veh_check', 'Daily vehicle check'), ('mot_expiry', 'MOT expiry')], max_length=16),
        ),
    ]
