# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0054_auto_20180127_1729'),
        ('datalive_geofence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceNotificationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(max_length=256)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalive_cust_veh.Customer')),
            ],
        ),
        migrations.AlterField(
            model_name='geofencegroup',
            name='geofences',
            field=models.ManyToManyField(null=True, to='datalive_cust_veh.Vehicle'),
        ),
        migrations.AlterField(
            model_name='geofencegroup',
            name='notifications_emails',
            field=models.ManyToManyField(blank=True, to='datalive_geofence.GeofenceNotificationEmail'),
        ),
    ]
