# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0063_merge_20180129_2331'),
        ('datalive_geofence', '0002_auto_20180129_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geofence',
            old_name='type',
            new_name='geofence_type',
        ),
        migrations.AddField(
            model_name='geofence',
            name='vehicles',
            field=models.ManyToManyField(null=True, to='datalive_cust_veh.Vehicle'),
        ),
        migrations.AlterField(
            model_name='geofencegroup',
            name='geofences',
            field=models.ManyToManyField(null=True, to='datalive_geofence.Geofence'),
        ),
    ]
