# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0064_remove_vehicle_odf'),
        ('datalive_geofence', '0003_auto_20180129_2354'),
    ]

    operations = [
        # JWF temp remove these fields as this bit already done
        #migrations.CreateModel(
        #    name='GeofeceGeofenceGroupMap',
        #    fields=[
        #        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #        ('geofence_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datalive_geofence.GeofenceGroup')),
        #        ('notifications_emails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datalive_geofence.GeofenceNotificationEmail')),
        #    ],
        #),
        #migrations.CreateModel(
        #    name='GeofenceVehicleMap',
        #    fields=[
        #        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #    ],
        #),


        # JWF Was, but manulally edited to be remove, Add
        #migrations.AlterField(
        #    model_name='geofence',
        #    name='vehicles',
        #    field=models.ManyToManyField(null=True, through='datalive_geofence.GeofenceVehicleMap', to='datalive_cust_veh.Vehicle'),
        #),

        #migrations.RemoveField(
        #    model_name='geofence',
        #    name='vehicles',
        #),


        # JWF Migrations beyond this point not run!!!!!

        #migrations.AddField(
        #    model_name='geofence',
        #    name='vehicles',
        #    field=models.ManyToManyField(null=True, to='datalive_cust_veh.Vehicle'),
        #),
        #migrations.AddField(
        #    model_name='geofencevehiclemap',
        #    name='geofence',
        #    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datalive_geofence.Geofence'),
        #),
        #migrations.AddField(
        #    model_name='geofencevehiclemap',
        #    name='vehicle',
        #    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datalive_cust_veh.Vehicle'),
        #),
    ]
