# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_vehicle_check', '0003_auto_20171123_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='checker_signature',
            field=models.FileField(null=True, upload_to='vehicle-reports/%Y/%m/%d/signature/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='driver_signature',
            field=models.FileField(null=True, upload_to='vehicle-reports/%Y/%m/%d/signature/'),
        ),
    ]
