# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_vehicle_check', '0003_auto_20171123_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='checker_signature',
            field=models.ImageField(null=True, upload_to='vehicle-check/signatures/%Y/%m/%d/signature/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='driver_signature',
            field=models.ImageField(null=True, upload_to='vehicle-check/signatures/%Y/%m/%d/signature/'),
        ),
        migrations.AlterField(
            model_name='reportphoto',
            name='photo',
            field=models.ImageField(upload_to='vehicle-check/photos/%Y/%m/%d/'),
        ),
    ]
