# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_vehicle_check', '0004_auto_20171127_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresponse',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='report',
            name='question_responses',
        ),
        migrations.DeleteModel(
            name='QuestionResponse',
        ),
    ]
