# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_vehicle_check', '0005_auto_20171127_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalive_vehicle_check.QuestionDefinitionAnswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalive_vehicle_check.QuestionDefinition')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='question_responses',
            field=models.ManyToManyField(related_name='reports', to='datalive_vehicle_check.QuestionResponse'),
        ),
    ]
