# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datalive_vehicle_check', '0006_auto_20171127_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='fixed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_damages', to=settings.AUTH_USER_MODEL),
        ),
    ]
