# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_vehicle_check', '0004_auto_20171127_2322'),
        ('datalive_vehicle_check', '0007_damage_fixed_by'),
    ]

    operations = [
    ]
