# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_vehicle_check', '0009_auto_20171129_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_damages', to=settings.AUTH_USER_MODEL),
        ),
    ]
