# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_vehicle_check', '0010_auto_20171129_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='bh',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='bw',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='bx',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='by',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
