# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_vehicle_check', '0011_auto_20171129_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='x',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='y',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
