# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_vehicle_check', '0013_auto_20171201_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatecheckreport',
            name='tractor',
        ),
        migrations.AddField(
            model_name='gatecheckreport',
            name='hub_photos',
            field=models.ManyToManyField(null=True, related_name='hub_gatecheck_reports', to='datalive_vehicle_check.ReportPhoto'),
        ),
        migrations.AddField(
            model_name='gatecheckreport',
            name='reg',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gatecheckreport',
            name='trailer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
