# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_vehicle_check', '0014_auto_20171201_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatecheckreport',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depot_gatecheck_reports', to='datalive_cust_veh.VehicleGroup'),
        ),
        migrations.AlterField(
            model_name='gatecheckreport',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_gatecheck_reports', to='datalive_cust_veh.VehicleGroup'),
        ),
    ]
