# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-29 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_vehicle_check', '0016_auto_20171229_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditsurveyreport',
            name='date',
        ),
    ]
