# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_vehicle_check', '0017_remove_auditsurveyreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsurveytemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
