# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-05 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_vehicle_check', '0019_auto_20180125_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='been_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
