# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataliveuser',
            name='first_name',
            field=models.CharField(default='J', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataliveuser',
            name='last_name',
            field=models.CharField(default='J', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataliveuser',
            name='short_name',
            field=models.CharField(default='J', max_length=32),
            preserve_default=False,
        ),
    ]
