# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-07-05 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0003_auto_20170704_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataliveuser',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='dataliveuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userprefs',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to=settings.AUTH_USER_MODEL),
        ),
    ]
