# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-07-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0004_auto_20170705_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_global_admin', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=False)),
                ('is_limited_user', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='dataliveuser',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datalive_auth.UserPermission'),
        ),
    ]
