# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-07-07 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0005_auto_20170707_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpermission',
            old_name='is_customer',
            new_name='is_customer_user',
        ),
    ]
