# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0008_olduserpassword_userresetpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataliveuser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 14, 15, 17, 7, 360393)),
        ),
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='token',
            field=models.CharField(default='4c1c5d8fd6301266b44ec3e5291c0c0643a426c283e86b083a58301d71e59493', max_length=1024),
        ),
    ]
