# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0009_auto_20170713_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 5, 12, 56, 14, 194739)),
        ),
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='token',
            field=models.CharField(default=b'8b105b10d43f4038ba4b61afc4fd2b4a4af052212c4d453c8ab896e9c7df9202', max_length=1024),
        ),
    ]
