# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0010_auto_20171004_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 17, 43, 38, 610923)),
        ),
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='token',
            field=models.CharField(default=b'fe0ea4338cf74193b5f5a5d51c0ca7a790e2a6ee5c7e488cbabd8d4759610d89', max_length=1024),
        ),
    ]
