# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 18:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0011_auto_20171022_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 4, 18, 23, 49, 470900)),
        ),
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='token',
            field=models.CharField(default=b'4594a5ab9e174339944bf07021c3390c5b7d198e76714da4b0fdb455d2c355e3', max_length=1024),
        ),
    ]
