# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 22:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0012_auto_20171103_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 4, 22, 40, 6, 867492)),
        ),
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='token',
            field=models.CharField(default=b'0512ce2105344571a1d72b862b49661305ac60488ea84ab4bc2336183603e1b2', max_length=1024),
        ),
    ]
