# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0013_auto_20171103_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataliveuser',
            name='username',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
