# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 23:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0014_auto_20171110_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 23, 40, 14, 530358)),
        ),
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='token',
            field=models.CharField(max_length=1024),
        ),
    ]
