# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 21:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0017_auto_20171113_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 21, 1, 23, 259641)),
        ),
    ]
