# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 23:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0018_auto_20171114_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 23, 42, 38, 173595)),
        ),
    ]
