# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 00:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0019_auto_20171114_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 16, 0, 5, 27, 355518)),
        ),
    ]
