# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 07:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0028_auto_20171115_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 16, 7, 28, 34, 836884)),
        ),
    ]
