# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 07:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0029_auto_20171115_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpermission',
            old_name='is_server',
            new_name='is_server_user',
        ),
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 16, 7, 29, 34, 381708)),
        ),
    ]
