# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0032_auto_20171115_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='userresetpasswordtoken',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='dataliveuser',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='module_users', to='datalive_auth.ModulePermission'),
        ),
    ]
