# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-18 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0033_auto_20171118_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermissionEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=256)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='datalive_auth.ModulePermission')),
            ],
        ),
    ]
