# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0008_auto_20171123_0844'),
        ('datalive_auth', '0034_modulepermissionendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataliveuser',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_regions', to='datalive_cust_veh.Region'),
        ),
    ]
