# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_auth', '0035_dataliveuser_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataliveuser',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='user_customers', to='datalive_cust_veh.Customer'),
        ),
        migrations.AlterField(
            model_name='dataliveuser',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='user_regions', to='datalive_cust_veh.Region'),
        ),
        migrations.AlterField(
            model_name='dataliveuser',
            name='vehicle_groups',
            field=models.ManyToManyField(blank=True, related_name='user_vehicle_groups', to='datalive_cust_veh.VehicleGroup'),
        ),
    ]
