# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0002_auto_20171021_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='solar_vista_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfault',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='equipmentfault',
            name='solar_vista_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
