# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0003_auto_20171004_1256'),
        ('datalive_defects', '0003_auto_20171021_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectsetting',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datalive_cust_veh.Customer'),
            preserve_default=False,
        ),
    ]
