# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0004_defectsetting_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectsetting',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datalive_cust_veh.Customer'),
        ),
    ]
