# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0005_auto_20171021_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectFault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalive_defects.Equipment')),
                ('fault', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalive_defects.EquipmentFault')),
            ],
        ),
        migrations.AlterField(
            model_name='defect',
            name='faults',
            field=models.ManyToManyField(to='datalive_defects.DefectFault'),
        ),
    ]
