# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0006_auto_20171021_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='faults',
            field=models.ManyToManyField(to='datalive_defects.EquipmentFault'),
        ),
    ]
