# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0007_auto_20171021_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='defect_image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='defect',
            name='other_details',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
