# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0008_auto_20171022_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='defect_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
