# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0009_auto_20171022_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='docfile',
        ),
        migrations.AlterField(
            model_name='defect',
            name='defect_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/defects/%Y/%m/%d'),
        ),
    ]
