# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0010_auto_20171122_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentDefinitionAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalive_defects.EquipmentDefinitionAnswers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalive_defects.EquipmentDefinition')),
            ],
        ),
        migrations.AddField(
            model_name='equipmentdefinition',
            name='answers',
            field=models.ManyToManyField(to='datalive_defects.EquipmentDefinitionAnswers'),
        ),
        migrations.AddField(
            model_name='defect',
            name='equip_faults',
            field=models.ManyToManyField(to='datalive_defects.EquipmentResponses'),
        ),
    ]
