# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0011_auto_20171123_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDefinitionFaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=500)),
                ('solar_vista_ref', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='equipmentresponses',
            old_name='question',
            new_name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipmentresponses',
            name='answer',
        ),
        migrations.AlterField(
            model_name='defect',
            name='faults',
            field=models.ManyToManyField(to='datalive_defects.DefectFault'),
        ),
        migrations.AlterField(
            model_name='equipmentdefinition',
            name='answers',
            field=models.ManyToManyField(to='datalive_defects.EquipmentDefinitionFaults'),
        ),
        migrations.DeleteModel(
            name='EquipmentDefinitionAnswers',
        ),
        migrations.AddField(
            model_name='equipmentresponses',
            name='fault',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datalive_defects.EquipmentDefinitionFaults'),
            preserve_default=False,
        ),
    ]
