# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0014_auto_20171123_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentDefinitionFaults',
            new_name='EquipmentDefinitionFault',
        ),
        migrations.RenameModel(
            old_name='EquipmentResponses',
            new_name='EquipmentResponse',
        ),
    ]
