# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0015_auto_20171123_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='customer',
        ),
        migrations.AddField(
            model_name='defect',
            name='sent_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
