# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0016_auto_20171123_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentdefinition',
            old_name='index',
            new_name='xlr_index',
        ),
    ]
