# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0017_auto_20171123_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='faults',
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_faults',
            field=models.ManyToManyField(to='datalive_defects.EquipmentResponse'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='sent_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
