# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0018_auto_20171123_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectsetting',
            name='customer',
        ),
        migrations.DeleteModel(
            name='DefectSetting',
        ),
    ]
