# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_defects', '0019_auto_20171123_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='defect_photo',
            field=models.ImageField(blank=True, null=True, upload_to='defects/photos/%Y/%m/%d'),
        ),
    ]
