# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0003_auto_20171004_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='contacts',
            field=models.ManyToManyField(null=True, to='datalive_cust_veh.Contact'),
        ),
        migrations.AlterField(
            model_name='vehiclegroup',
            name='contacts',
            field=models.ManyToManyField(null=True, to='datalive_cust_veh.Contact'),
        ),
    ]
