# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0004_auto_20171027_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to='datalive_cust_veh.Contact'),
        ),
        migrations.AlterField(
            model_name='vehiclegroup',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to='datalive_cust_veh.Contact'),
        ),
    ]
