# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0005_auto_20171028_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='solar_vista_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclegroup',
            name='solar_vista_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
