# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0006_auto_20171028_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='allocated_depot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='latest_odometer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='latest_odometer_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='livery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalive_cust_veh.Livery'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mot_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
