# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0007_auto_20171113_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveryview',
            name='img_filename',
        ),
        migrations.AlterField(
            model_name='liveryview',
            name='img',
            field=models.ImageField(upload_to='vehicle-reports/%Y/%m/%d/'),
        ),
    ]
