# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0009_liveryview_view_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='mot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
