# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-24 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0010_auto_20171123_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='front_tyre_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='front_tyre_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('DEI', 'Deisel'), ('PET', 'Petrol')], default='DEI', max_length=3),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='load_capacity',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rear_tyre_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rear_tyre_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
