# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-24 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0013_auto_20171124_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalive_cust_veh.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='FAQActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionValue', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalive_cust_veh.FAQ')),
            ],
        ),
        migrations.AddField(
            model_name='faqactions',
            name='faqDescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalive_cust_veh.FAQDescription'),
        ),
    ]
