# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0014_auto_20171124_1558'),
        ('datalive_cust_veh', '0011_auto_20171127_2322'),
    ]

    operations = [
    ]
