# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0016_depotcontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepotContact',
            new_name='VehicleGroupContact',
        ),
    ]
