# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0017_auto_20171203_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclegroupcontact',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
