# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0018_vehiclegroupcontact_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='policy_document',
            field=models.ImageField(max_length=256, null=True, upload_to=b''),
        ),
    ]
