# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-10 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0019_insurance_policy_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicyNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50, null=True)),
            ],
        ),
        # migrations.RenameField(
        #     model_name='customer',
        #     old_name='address',
        #     new_name='address1',
        # ),
        migrations.RenameField(
            model_name='faqactions',
            old_name='actionValue',
            new_name='action_value',
        ),
        migrations.RemoveField(
            model_name='faqactions',
            name='faqDescription',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='vehiclegroup',
            name='contacts',
        ),
         migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='address1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='county',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faqactions',
            name='action_display_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='faqactions',
            name='action_type',
            field=models.CharField(choices=[('TEL', 'Phone number'), ('WEB', 'Web URL'), ('EMAIL', 'Email link')], default='TEL', max_length=5),
        ),
        migrations.AddField(
            model_name='faqdescription',
            name='actions',
            field=models.ManyToManyField(blank=True, to='datalive_cust_veh.FAQActions'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='additional_info',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalive_cust_veh.Customer'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='customer_accident_phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='vehicle-hero-images'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_due_odo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegroup',
            name='vehicle_group_contacts',
            field=models.ManyToManyField(blank=True, to='datalive_cust_veh.VehicleGroupContact'),
        ),
        migrations.AddField(
            model_name='vehiclegroupcontact',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faqdescription',
            name='description',
            field=models.TextField(max_length=1100),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='policy_document',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='policy_document_url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='datalive_cust_veh.Contact'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('DIE', 'Diesel'), ('PET', 'Petrol')], default='DEI', max_length=3),
        ),
        migrations.AlterField(
            model_name='vehiclegroupcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='vehiclegroupcontact',
            name='web_url',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='vehicletracker',
            name='deinstalled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletracker',
            name='installed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalive_cust_veh.Customer'),
        ),
        migrations.AddField(
            model_name='notificationemail',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalive_cust_veh.Customer'),
        ),
        migrations.AddField(
            model_name='insurancepolicynumber',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datalive_cust_veh.Insurance'),
        ),
        migrations.AddField(
            model_name='insurancepolicynumber',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalive_cust_veh.VehicleCategory'),
        ),
        migrations.AddField(
            model_name='faq',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalive_cust_veh.VehicleCategory'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalive_cust_veh.VehicleCategory'),
        ),
        migrations.AddField(
            model_name='vehiclegroup',
            name='notifications_emails',
            field=models.ManyToManyField(blank=True, to='datalive_cust_veh.NotificationEmail'),
        ),
    ]
