# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-11 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0021_auto_20171211_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vehiclegroup',
            name='vehicle_group_contacts',
            field=models.ManyToManyField(blank=True, related_name='vehicle_group_contacts', to='datalive_cust_veh.VehicleGroupContact'),
        ),
    ]
