# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0022_auto_20171211_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='livery',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='vehicle-hero-images'),
        ),
    ]
