# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0023_auto_20171212_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customer'),
        ),
        migrations.AddField(
            model_name='insurancepolicynumber',
            name='additional_info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
