# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0025_auto_20171212_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('is_maintenance_control', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalive_cust_veh.Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='region',
            name='contacts',
        ),
        migrations.AddField(
            model_name='region',
            name='notifications_emails',
            field=models.ManyToManyField(blank=True, to='datalive_cust_veh.NotificationEmail'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='customer',
            name='contacts',
            field=models.ManyToManyField(to='datalive_cust_veh.CustomerContact'),
        ),
    ]
