# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0026_auto_20171212_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclegroupcontact',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='vehiclegroupcontact',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='vehiclegroupcontact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vehiclegroupcontact',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vehiclegroupcontact',
            name='county',
        ),
        migrations.RemoveField(
            model_name='vehiclegroupcontact',
            name='postcode',
        ),
        migrations.AddField(
            model_name='vehiclegroupcontact',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datalive_cust_veh.Address'),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datalive_cust_veh.Address'),
        ),
    ]
