# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0027_auto_20171212_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclegroup',
            name='ref_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
