# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0028_auto_20171212_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclegroup',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
