# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0029_auto_20171212_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contacts',
            new_name='primary_contacts',
        ),
        migrations.RemoveField(
            model_name='customercontact',
            name='is_maintenance_control',
        ),
        migrations.RemoveField(
            model_name='vehiclegroupcontact',
            name='is_maintenance_control',
        ),
        migrations.AddField(
            model_name='customer',
            name='maintenance_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_control', to='datalive_cust_veh.CustomerContact'),
        ),
    ]
