# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0030_auto_20171212_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='primary_contacts',
            new_name='contacts',
        ),
    ]
