# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0031_auto_20171212_1907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerContact',
            new_name='Contact',
        ),
    ]
