# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0032_auto_20171212_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='county',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postcode',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_contact', to='datalive_cust_veh.Contact'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customer/logos/'),
        ),
    ]
