# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0033_auto_20171212_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datalive_cust_veh.Address'),
        ),
    ]
