# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0035_auto_20171212_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='address',
        ),
    ]
