# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0036_remove_insurance_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datalive_cust_veh.Address'),
        ),
    ]
