# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0039_auto_20171212_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='policy_document_url',
        ),
    ]
