# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0040_remove_insurance_policy_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customer/logos'),
        ),
    ]
