# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0041_auto_20171214_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='service_due_date',
        ),
    ]
