# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0044_remove_vehicle_service_due_odo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='service_due_odo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
