# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-07 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0047_auto_20180107_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='gross_vehicle_weight',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
