# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0049_vehicle_lease_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='rear_tyre_size',
        ),
    ]
