# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0050_remove_vehicle_rear_tyre_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='front_tyre_size',
            new_name='tyre_size',
        ),
    ]
