# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0051_auto_20180108_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datalive_cust_veh.Address')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='lease_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datalive_cust_veh.LeaseCompany'),
        ),
    ]
