# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0052_auto_20180108_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecompany',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalive_cust_veh.Customer'),
        ),
    ]
