# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0053_leasecompany_customer'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='vehicle',
        #     name='odf',
        # ),
        # migrations.AlterField(
        #     model_name='livery',
        #     name='views',
        #     field=models.ManyToManyField(related_name='livery_views', to='datalive_cust_veh.LiveryView'),
        # ),
        # migrations.AlterField(
        #     model_name='vehicle',
        #     name='fuel_type',
        #     field=models.CharField(choices=[('DIE', 'Diesel'), ('PET', 'Petrol')], default='DIE', max_length=3),
        # ),
    ]
