# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0054_auto_20180120_1447'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='vehicle',
        #     name='odf',
        # ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
