# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0055_auto_20180121_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LiverySchematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='livery-vehicle-hero-images')),
            ],
        ),
        migrations.CreateModel(
            name='SchematicView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('view_name', models.CharField(choices=[('FRONT', 'Front View'), ('DRIVER', 'Driver View'), ('REAR', 'Rear View'), ('PASSENGER', 'Passenger View'), ('TOP', 'Top View')], max_length=10, null=True)),
                ('img', models.ImageField(upload_to='vehicle-schematics/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleManufacturerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, max_length=110)),
                ('type', models.CharField(choices=[('BIK', 'Bike'), ('CAR', 'Car'), ('VAN', 'Van'), ('STR', 'Small Truck'), ('MTR', 'Medium Truck'), ('LTR', 'Large Truck'), ('TNK', 'Tanker'), ('TRL', 'Trailer'), ('CON', 'Construction Equiptment'), ('RDR', 'Road Roller'), ('BUS', 'Bus'), ('BOT', 'Boat')], default='VAN', max_length=3)),
                ('load_capacity', models.FloatField(blank=True, default=0.0, max_length=10, null=True)),
                ('gross_vehicle_weight', models.FloatField(blank=True, max_length=10, null=True)),
                ('fuel_type', models.CharField(choices=[('DIE', 'Diesel'), ('PET', 'Petrol')], default='DIE', max_length=3)),
                ('front_tyre_pressure', models.IntegerField(blank=True, null=True)),
                ('rear_tyre_pressure', models.IntegerField(blank=True, null=True)),
                ('tyre_size', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSchematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hero_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='vehicle-hero-images')),
            ],
        ),
        migrations.RenameModel(
            old_name='VehicleCategory',
            new_name='DriverCategory',
        ),
        migrations.RemoveField(
            model_name='livery',
            name='views',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='vehicle_category',
            new_name='driver_category',
        ),
        migrations.RenameField(
            model_name='insurancepolicynumber',
            old_name='vehicle_category',
            new_name='driver_category',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_category',
            new_name='driver_category',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='front_tyre_pressure',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='gross_vehicle_weight',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='livery',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='load_capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rear_tyre_pressure',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='tyre_size',
        ),
        migrations.AlterField(
            model_name='leasecompany',
            name='name',
            field=models.CharField(db_index=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='latest_odometer_source',
            field=models.CharField(choices=[('MAN', 'Driver manually entered'), ('GPS', 'From tracker GPS'), ('OBD', 'From tracker on OBD'), ('CAN', 'From tracker on J1939 CAN Bus')], default='MAN', max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='Livery',
        ),
    ]
