# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0057_auto_20180125_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemanufacturermodel',
            old_name='schematics',
            new_name='schematic',
        ),
        migrations.RenameField(
            model_name='vehiclemanufacturermodel',
            old_name='type',
            new_name='vehicle_type',
        ),
    ]
