# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0058_auto_20180125_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemanufacturermodel',
            name='vehicle_model_contacts',
            field=models.ManyToManyField(blank=True, related_name='vehicle_model_contacts', to='datalive_cust_veh.VehicleGroupContact'),
        ),
    ]
