# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-26 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0059_vehiclemanufacturermodel_vehicle_model_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemanufacturermodel',
            name='fuel_type',
            field=models.CharField(choices=[('DIE', 'Diesel'), ('PET', 'Petrol'), ('ELE', 'Electric')], default='DIE', max_length=3),
        ),
    ]
