# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0060_auto_20180125_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemanufacturermodel',
            name='schematics',
            field=models.ManyToManyField(blank=True, related_name='vehicle_schematic_views', to='datalive_cust_veh.SchematicView'),
        ),
    ]
