# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-27 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0061_auto_20180125_1249'),
        ('datalive_cust_veh', '0060_auto_20180126_1346'),
    ]

    operations = [
    ]
