# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0054_auto_20180127_1729'),
        ('datalive_cust_veh', '0062_merge_20180127_2029'),
    ]

    operations = [
    ]
