# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0063_merge_20180129_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='odf',
        ),
    ]
