# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-04 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalive_cust_veh', '0064_remove_vehicle_odf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['registration']},
        ),
        migrations.AlterField(
            model_name='vehiclegroupcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclegroupcontact',
            name='web_url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
